repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      stages: [pre-commit]
    # Run the formatter.
    - id: ruff-format
      args: [--target-version, py311]
      stages: [pre-commit]

