repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      additional_dependencies: [ "python==3.11" ]
    # Run the formatter.
    - id: ruff-format
      additional_dependencies: [ "python==3.11" ]
